### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by DougUOT**
Uploading images and Roadmap updated

### CODE REVIEW

**Comment by DougUOT** [comment]
Uploading images and Roadmap updated

**Comment by DougUOT** [comment]
Uploading images and Roadmap updated

**Review by ByronKrauskopf — APPROVED** [review]
reviewed and approved

**Comment by DougUOT** [comment]
approved

**Review by jathuson — APPROVED** [review]

**Comment by DougUOT** [comment]
approved

**Comment by DougUOT** [comment]
approved

**Review by DrZubi — APPROVED** [review]

**Pull request merged**
